### ISSUE TITLE
NO such method error

### ISSUE THREAD

**Issue by SriKrishnaCovalense** [opentok/learning-opentok-android#23]
java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)

**Comment by senthil4589** [comment]
same problem. Please help me

**Comment by michaeljolley** [comment]
Closing as stale. Please open a new issue if the problem or question persists.
