### ISSUE TITLE
There is no "camera-capturer" branch as described in the tutorial.

### ISSUE THREAD

**Issue by timowilson-fluke** [opentok/learning-opentok-android#65]

**Comment by MaximSysoev** [comment]
Add camera-capturer branch, please.

**Comment by dkroz** [comment]
If you're looking for CustomVideoCapturer class:
https://github.com/opentok/opentok-android-sdk-samples/tree/master/Custom-Video-Driver/CustomVideoDriverLib/src/main/java/com/example/tokbox/CustomVideoDriverLib
