### ISSUE TITLE
Is there a way to support USB camera

### ISSUE THREAD

**Issue by Kevin-Kuloth** [opentok/learning-opentok-android#68]
Is there a way to support USB camera to publish

**Comment by igorwojda** [comment]
This repository is no longer maintained. For OpenTok Android SDK samples check [opentok-android-sdk-samples](https://github.com/opentok/opentok-android-sdk-samples) repository.

If you still experience the problem please open a [support request](https://support.tokbox.com/hc/en-us/requests/new) providing detailed hardware information.
